# Generated by Django 4.2.1 on 2023-05-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.IntegerField(blank=True, null=True)),
                ('studentName', models.CharField(blank=True, max_length=50, null=True)),
                ('studentYear', models.IntegerField(blank=True, null=True)),
                ('studentSection', models.IntegerField(blank=True, null=True)),
                ('studentImage', models.ImageField(blank=True, null=True, upload_to='photos/%y/%m/%d')),
            ],
        ),
        migrations.DeleteModel(
            name='attended',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
